// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sjxeupeggseedybibyzx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNqeGV1cGVnZ3NlZWR5YmlieXp4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4MjEyODgsImV4cCI6MjA2MDM5NzI4OH0.K4cRPm0BQQgAv5qhnI7OTEG5ZACoznhU-ZvVXgFDmXs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);